apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-api-deployment
  labels:
    app: product-service-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-service-api
  template:
    metadata:
      labels:
        app: product-service-api
    spec:
      containers:
      - name: product-service-api
        image: fhmq9demoregistry.azurecr.io/fhmq9demo/productserviceapi:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        restartPolicy: OnFailure
