version: '3.4'

services:
  reverse.proxy:
    image: fhmq9demo/reverseproxy
    build:
      context: .
      dockerfile: proxy/reverse.proxy/Dockerfile
    ports:
      - "80:80"
      - "81:443"
    network_mode: "host"
    restart: always
    depends_on:
      - agentservice.api
      - masterservice.api
      - productservice.api
      
  agentservice.api:
    image: fhmq9demo/agentserviceapi
    build:
      context: .
      dockerfile: source/AgentService.WebApi/Dockerfile
    ports:
      - "8080:80"
      - "2001:443"
    network_mode: "host"

  masterservice.api:
    image: fhmq9demo/masterserviceapi
    build:
      context: .
      dockerfile: source/MasterService.WebApi/Dockerfile
    ports:
     - "8080:80"
     - "3001:443"
    network_mode: "host"
  
  productservice.api:
    image: fhmq9demo/productserviceapi
    build:
      context: .
      dockerfile: source/ProductService.WebApi/Dockerfile
    ports:
      - "8080:80"
      - "4001:443"
    network_mode: "host"
  
    # ${DOCKER_REGISTRY-}

    #  volumes:
    #   - ~/.aspnet/https:/root/.aspnet/https:ro
    #   - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro