apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    app: reverseproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: fhmq9demoregistry.azurecr.io/fhmq9demo/reverseproxy:latest
        resources:
          limits:
            cpu: "500m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always