apiVersion: v1
kind: Service
metadata:
  name: public-reverseproxy
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: reverseproxy
  type: LoadBalancer

#kubectl rollout restart deployment/<deployment-name>
#kubectl exec --stdin --tty reverseproxy-deployment-dfc54d47c-ldntn -- /bin/sh
  #kubectl expose deployment agent-service-api-deployment --type=LoadBalancer --name=public-agent-service-api