apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-service-api-deployment
  labels:
    app: agent-service-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agent-service-api
  template:
    metadata:
      labels:
        app: agent-service-api
    spec:
      containers:
      - name: agent-service-api
        image: fhmq9demoregistry.azurecr.io/fhmq9demo/agentserviceapi:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          request:
            cpu: "200m"
        ports:
        - containerPort: 80
