apiVersion: v1
kind: Service
metadata:
  name: agent-service-api
  labels:
    app: agent-service-api
spec:
  selector:
    app: agent-service-api
    component: agent-service-api
  ports:
  - port: 8080
    targetPort: 80


